Pour réaliser le bras du drone :

Faire glisser le cylindre orange du panneau latéral de droite sur le plan de construction, 
puis cliquer sur les rectangles blancs pour donner au cylindre, une base de 10.00 en largeur et en profondeur, la hauteur n’a pas besoin d’être modifiée.

(https://github.com/emlyon/makerstime/blob/master/Drone%20Gifs/01.gif)

D’autre part, il faut modifier le réglage de la grille en cliquant sur la boîte située à côté de 
« Grille d’accrochage 1,0 mm» et sélectionner 0,5 mm.

Puis, sélectionner le cylindre gris dans le panneau de droite.
Toujours à l’aide des carrés blancs, il faut changer sa base en 7.50 en largeur et en profondeur.
À l’aide de la flèche noire au sommet, surélever le cylindre de 2.00 en hauteur par rapport au plan de travail.


Nous allons maintenant extruder le cylindre orange.

En maintenant le bouton gauche de la souris, sélectionner les deux cylindres.
Ils devraient apparaître tous deux entourés d’un trait couleur cyan. 
Appuyer sur le bouton « Aligné » ( ou bien la touche L )
Une grille de sélection apparaît sur le rectangle au niveau du plan de travail, cliquer sur les cercles se situant au milieu des segments du rectangle.
Le cylindre gris se situe maintenant au milieu du cylindre orange.

Sélectionner ensuite l’icône « Regrouper » en haut à droite ( ou la touche Ctrl + G )

Le cylindre orange est maintenant creux.


Nous allons maintenant ajouter des aérations.

Par conséquent, il faut prendre le cylindre gris du panneau latéral.

Grâce aux doubles flèches courbes, il est nécessaire d’effectuer une rotation de 90°, 
afin de lui donner une hauteur de 8.00, une largeur de 5.00 et une profondeur de 20.00.

Grâce à la flèche noire, le surélever de 1.00.

Avec l’outil aligné, mettre le cylindre gris au centre du cylindre orange.

Dupliquer le cylindre gris avec le bouton en haut à gauche ( ou la touche Ctrl + D )

Cliquer sur la flèche noire et surélever le nouveau cylindre gris de 11.00.

Sélectionner les trois cylindres et cliquer de nouveau sur « Regrouper ».

Le cylindre orange est maintenant percé de quatre ovales.


Nous allons maintenant réaliser le bras.

Sélectionner la boîte rouge dans le panneau latéral droit.

Après l’avoir placée sur le plan de travail, il faut lui donner une largeur de 6.50, une hauteur de 6.50 et une profondeur de 20.00.

Prendre un cube gris, il est nécessaire de lui donner les dimensions suivantes : 
3.50 en largeur, 3.50 hauteur et 10 profondeur. 
